/*
 * MainFrame.java
 *
 * Created on 27/01/2010, 10:21:24 PM
 */
package com.usyd.main;

import com.usyd.log.Appender;
import com.usyd.log.ProgressUpdater;
import com.usyd.action.SearchCore;
import com.usyd.type.LoginType;
import com.usyd.unit.ArgumentUnit;
import com.usyd.unit.DatePairs;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;

/**
 *
 * @author min
 */
public class MainFrame extends javax.swing.JFrame {

    private List<String> companies;

    public List<String> getCompanies() {
        return companies;
    }

    public void setCompanies(List<String> companies) {
        this.companies = companies;
    }

    /** Creates new form MainFrame */
    public MainFrame() {
        initDates();
        initComponents();

        this.FromDD.setSelectedIndex(0);
        this.FromMM.setSelectedIndex(0);
        this.FromYYYY.setSelectedIndex(0);
        this.ToDD.setSelectedIndex(30);
        this.ToMM.setSelectedIndex(11);
        this.ToYYYY.setSelectedIndex(28);



        argument = new ArgumentUnit();
        argument.setType((LoginType) proxyComboBox.getSelectedItem());
        com.usyd.log.Logger.registerAppender(new Appender() {

            public void append(final String msg) {
                Runnable doUpdate = new Runnable() {

                    public void run() {
                        int lines = 1000;
                        textArea.append(msg);
                        Document doc = textArea.getDocument();
                        int cnt = textArea.getLineCount();
                        int diff = cnt - lines;
                        if (diff > 0) {
                            try {
                                doc.remove(0, textArea.getLineEndOffset(diff - 1));
                            } catch (BadLocationException ex) {
                                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        textArea.setCaretPosition(textArea.getText().length());
                    }
                };
                SwingUtilities.invokeLater(doUpdate);
            }
        });

        com.usyd.log.Logger.registerProgressUpdater(new ProgressUpdater() {

            public void finished(final int total, final int finished, final String name) {
                Runnable doUpdate = new Runnable() {

                    public void run() {
                        pBar.setMaximum(total);
                        pBar.setValue(finished);
//                        pBar.setToolTipText( "retrieving articles about '" + name + "'");
                        pBar.setString(name + " (" + finished + "/" + total + ")");
                    }
                };
                SwingUtilities.invokeLater(doUpdate);
            }
        });
        pBar.setValue(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        openBtn = new javax.swing.JButton();
        startBtn = new javax.swing.JButton();
        pBar = new javax.swing.JProgressBar();
        jCheckBox1 = new javax.swing.JCheckBox();
        proxyComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        FromDD = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FromMM = new javax.swing.JComboBox();
        FromYYYY = new javax.swing.JComboBox();
        ToDD = new javax.swing.JComboBox();
        ToMM = new javax.swing.JComboBox();
        ToYYYY = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Factiva");

        textArea.setColumns(20);
        textArea.setEditable(false);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        openBtn.setText("Open CSV File");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });

        startBtn.setText("Start");
        startBtn.setEnabled(false);
        startBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBtnActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Fuzzy Search");
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(openBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(startBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(openBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(startBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1)))
                .addContainerGap())
        );

        proxyComboBox.setModel(new javax.swing.DefaultComboBoxModel(new LoginType[] { LoginType.USYD, LoginType.USYDPROXY, LoginType.UNSW, LoginType.UNSWPROXY }));
        proxyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proxyComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Proxy:");

        FromDD.setModel(new javax.swing.DefaultComboBoxModel(dates));

        jLabel2.setText("From(dd/mm/yyyy)");

        jLabel3.setText("To (dd/mm/yyyy)");

        FromMM.setModel(new javax.swing.DefaultComboBoxModel(months));

        FromYYYY.setModel(new javax.swing.DefaultComboBoxModel(years));

        ToDD.setModel(new javax.swing.DefaultComboBoxModel(dates));

        ToMM.setModel(new javax.swing.DefaultComboBoxModel(months));

        ToYYYY.setModel(new javax.swing.DefaultComboBoxModel(years));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(proxyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FromDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FromYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ToYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(proxyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(FromDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(FromMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FromYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToYYYY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        JFileChooser fileopen = new JFileChooser();
        FileFilter filter = new FileNameExtensionFilter("csv files", "csv");
        fileopen.addChoosableFileFilter(filter);
        fileopen.setCurrentDirectory(new File("."));
        int ret = fileopen.showDialog(this, "Open file");

        if (ret == JFileChooser.APPROVE_OPTION) {
            csvFile = fileopen.getSelectedFile();
            try {
                BufferedReader rd = new BufferedReader(new FileReader(csvFile));
                String line;
                StringBuffer lines = new StringBuffer();
                companies = new ArrayList<String>();
                while ((line = rd.readLine()) != null) {
                    line.replaceAll("/", "#");
                    line.replaceAll("\"", "#");
                    companies.add(line);
                    lines.append(line);
                    lines.append(System.getProperty("line.separator"));
                }
                //textArea.setText(lines.toString());
                startBtn.setEnabled(true);

            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_openBtnActionPerformed
    SwingWorker worker;
    private void startBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBtnActionPerformed

        if (argument.getType().getCode() == LoginType.USYD.getCode()
                || argument.getType().getCode() == LoginType.USYDPROXY.getCode()) {
            PasswordPanel passPanel = new PasswordPanel();
            int action = JOptionPane.showConfirmDialog(null, passPanel, "Enter User Name and Password", JOptionPane.OK_CANCEL_OPTION);
            if (action < 0) {
                return;
            } else {
                user = passPanel.getUser();
                pass = passPanel.getPassword();
                if (user.trim().length() == 0 || pass.trim().length() == 0) {
                    return;
                }
            }
        } else {
            user = "";
            pass = "";
        }

        proxyComboBox.setEnabled(false);
        startBtn.setEnabled(false);
        pBar.setStringPainted(true);

        worker = new SwingWorker<String, Void>() {

            @Override
            public String doInBackground() throws InterruptedException {
                argument.setCompanyList(companies);

                int fromD = Integer.parseInt((String) FromDD.getSelectedItem());
                int fromM = Integer.parseInt((String) FromMM.getSelectedItem());
                int fromY = Integer.parseInt((String) FromYYYY.getSelectedItem());

                int toD = Integer.parseInt((String) ToDD.getSelectedItem());
                int toM = Integer.parseInt((String) ToMM.getSelectedItem());
                int toY = Integer.parseInt((String) ToYYYY.getSelectedItem());


                argument.setDatePairs(new DatePairs(fromY, fromM, fromD, toY, toM, toD));
                argument.setUser(user);
                argument.setPass(pass);
                FromDD.setEnabled(false);
                FromMM.setEnabled(false);
                FromYYYY.setEnabled(false);
                ToDD.setEnabled(false);
                ToMM.setEnabled(false);
                ToYYYY.setEnabled(false);
                SearchCore search = new SearchCore(argument);
                search.start(jCheckBox1.isSelected());
                return null;
            }

            @Override
            public void done() {
//                System.out.println("done!");
            }
        };
        worker.execute();
    }//GEN-LAST:event_startBtnActionPerformed

    private void proxyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proxyComboBoxActionPerformed
        // TODO add your handling code here:
        argument.setType((LoginType) proxyComboBox.getSelectedItem());
    }//GEN-LAST:event_proxyComboBoxActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox FromDD;
    private javax.swing.JComboBox FromMM;
    private javax.swing.JComboBox FromYYYY;
    private javax.swing.JComboBox ToDD;
    private javax.swing.JComboBox ToMM;
    private javax.swing.JComboBox ToYYYY;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton openBtn;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JComboBox proxyComboBox;
    private javax.swing.JButton startBtn;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    private File csvFile;
    private String user;
    private String pass;
    private ArgumentUnit argument;
    private String[] dates;
    private String[] years;
    private String[] months;

    private void initDates() {
        dates = new String[31];
        int index = 0;
        for (int i = 1; i <= 31; i++) {
            dates[index++] = i + "";
        }
        index = 0;
        months = new String[12];
        for (int i = 1; i <= 12; i++) {
            months[index++] = i + "";
        }
        index = 0;
        years = new String[41];
        for (int i = 1980; i <= 2020; i++) {
            years[index++] = i + "";
        }
    }
}
